name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: 

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Upgrade pip, setuptools, wheel (system environment)
        run: pip install --upgrade pip setuptools wheel

      - name: Setup Python with uv
        run: uv python install

      - name: Sync dev + extras
        run: uv sync --dev --all-extras

      - name: Install build
        run: uv run pip install build

      # - name: Install pdm-backend
      #   run: uv run pip install pdm-backend

      - name: Generate Proto Files
        run: uv run bash ./generate_proto.sh

      - name: Build wheel and sdist
        run: uv run python -m build

      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_API_TOKEN }}
