name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install build, pdm-backend, and grpcio-tools
        run: pip install build pdm-backend grpcio-tools
        continue-on-error: true

      - name: Generate Protobuf (if needed)
        run: bash ./generate_proto.sh
        continue-on-error: true

      - name: Build wheel and sdist
        run: python -m build
        continue-on-error: true

      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_API_TOKEN }}
