name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install setuptools wheel
        run: pip install --upgrade pip setuptools wheel

      - name: Setup Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Install build & pdm-backend into uv
        run: uv run pip install build pdm-backend

      - name: Generate Protobuf (if needed)
        run: bash ./generate_proto.sh

      - name: Build wheel and sdist
        run: uv run python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

